id: IE82182A1
legacy_id: P006927
ocr_import_info:
  bdrc_scan_id: W1CZ2163
  source: bdrc
  ocr_info:
    timestamp: '2020-03-28T21:08:06'
    imagesfolder: images
  batch_id: batch001
  software_id: vision
  expected_default_language: bo
  op_import_options: {}
  op_import_version: 1.0.0
default_language: bo
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2022-08-30T19:13:25.491932+00:00'
last_modified: 2022-08-31 03:13:41.583911
parser: https://github.com/OpenPecha/Toolkit/blob/7f57883d84bc10351527a49ee6ce970ace404e50/openpecha/formatters/google_ocr.py
source_metadata:
  id: http://purl.bdrc.io/resource/W1CZ2163
  status: http://purl.bdrc.io/admindata/StatusReleased
  access: http://purl.bdrc.io/admindata/AccessOpen
  reproduction_of: http://purl.bdrc.io/resource/MW1CZ2163
  copyright_status: http://purl.bdrc.io/resource/CopyrightPublicDomain
  title: འདས་ལོག་སངས་རྒྱས་ཆོས་འཛོམས་ཀྱི་རྣམ་ཐར།
  author: སངས་རྒྱས་ཆོས་འཛོམས།
statistics:
  ocr_word_mean_confidence_index: 0.9695575953892892
  ocr_word_median_confidence_index: 0.9800000190734863
quality: null
bases:
  I1CZ2293:
    source_metadata:
      id: http://purl.bdrc.io/resource/I1CZ2293
      total_pages: 154
      volume_number: 1
      volume_pages_bdrc_intro: 2
    order: 1
    base_file: I1CZ2293.txt
    statistics:
      ocr_word_median_confidence_index: 0.9800000190734863
      ocr_word_mean_confidence_index: 0.9695575953892892
    legacy_id: v001
copyright:
  status: Public domain
  notice: Public domain
  info_url: https://creativecommons.org/publicdomain/mark/1.0/
license: CC0
