id: IE82182A1
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T21:09:01+00:00'
last_modified: '2022-06-08T12:34:31.220956+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1CZ2163
  title: འདས་ལོག་སངས་རྒྱས་ཆོས་འཛོམས་ཀྱི་རྣམ་ཐར
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    E4D1:
      image_group_id: I1CZ2293
      title: ''
      total_pages: 154
      order: 1
      base_file: E4D1.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
