id: P006927
initial_creation_type: ocr
source_metadata:
  id: bdr:W1CZ2163
  title: འདས་ལོག་སངས་རྒྱས་ཆོས་འཛོམས་ཀྱི་རྣམ་ཐར
  author: ''
  volumes:
    b650ba0e43d84172bfdc780f1dda668e:
      image_group_id: I1CZ2293
      title: ''
      volume_number: 1
      total_pages: 154
      base_file: v001.txt
